# -*- coding: utf-8 -*-
"""CA2ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PJBXDuiei6ElgIRFMtS9sqyL2cVhBB-q
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("advertising.csv")
df.head()

df.shape

df.describe()

sns.pairplot(df, x_vars=['TV', 'Radio','Newspaper'], y_vars='Sales', kind='scatter')
plt.show()

df['TV'].plot.hist(bins=10, color="green", xlabel="TV")

df['Radio'].plot.hist(bins=10, color="orange", xlabel="Radio")

df['Newspaper'].plot.hist(bins=10,color="black", xlabel="newspaper")

sns.heatmap(df.corr(),annot = True)
plt.show()

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['TV']], df[['Sales']], test_size = 0.3,random_state=0)

print(X_train)

print(y_train)

print(X_test)

print(y_test)

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,y_train)

res= model.predict(X_test)
print(res)

print("Accuracy Score: ", model.score(X_test,y_test)*100)

plt.style.use('dark_background')
plt.grid()
plt.plot(res)

plt.style.use('default')
plt.grid()
plt.scatter(X_test, y_test)

plt.show()